build: off
cache:
    - c:\php -> appveyor.yml
    - '%LOCALAPPDATA%\Composer\files -> appveyor.yml'

clone_folder: c:\projects\database

services:
    - mssql2008r2sp2
#    - mssql2012sp1
#    - mssql2014
#    - mssql2016
    - mysql

init:
    - SET PATH=c:\php;%PATH%
    - SET PHP=1
    - SET ANSICON=121x90 (121x90)

install:
    # Install PHP
    - IF EXIST c:\php (SET PHP=0) ELSE (SET PHP=1)
    - IF %PHP%==1 mkdir c:\php
    - IF %PHP%==1 cd c:\php
    - IF %PHP%==1 curl https://windows.php.net/downloads/releases/archives/php-7.1.5-Win32-VC14-x64.zip --output php.zip
    - IF %PHP%==1 7z x php.zip >nul
    - IF %PHP%==1 echo extension_dir=ext >> php.ini
    - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
    - IF %PHP%==1 curl https://github.com/Microsoft/msphpsql/releases/download/v4.3.0/Windows-7.1.zip -L --output sqlsrv.zip
    - IF %PHP%==1 7z x sqlsrv.zip >nul
    - IF %PHP%==1 copy Windows-7.1\x64\php_pdo_sqlsrv_71_ts.dll ext\php_pdo_sqlsrv_ts.dll
    - IF %PHP%==1 del /Q *.zip
    - cd c:\projects\database

    # Install Nette Tester
    - appveyor DownloadFile https://getcomposer.org/composer.phar
    - php composer.phar install --prefer-dist --no-interaction --no-progress

    # Create databases.ini
    - copy tests\databases.appveyor.ini tests\Database\databases.ini

test_script:
    - vendor\bin\tester tests -s -c tests\php-win.ini

on_failure:
    # Print *.actual content
    - for /r %%x in (*.actual) do ( type "%%x" )
